# Generated by Django 3.2.5 on 2021-07-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRegister',
            fields=[
                ('JobRegisterId', models.AutoField(primary_key=True, serialize=False)),
                ('Company_Name', models.CharField(max_length=100)),
                ('Job_Description', models.TextField()),
                ('CompanyLogo', models.ImageField(upload_to='pics')),
                ('Company_EmailId', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidates_Firstname', models.CharField(max_length=100)),
                ('Candidates_lastname', models.CharField(max_length=100)),
                ('Candidates_EmailId', models.EmailField(max_length=254)),
            ],
        ),
    ]
